### ISSUE TITLE
Uncaught TypeError: L is not a function

### ISSUE THREAD

**Issue by OnkelTem** [jonatkins/ingress-intel-total-conversion#1062] opened 2015-10-12 23:16 UTC
I noticed this error message in the console when using IITC:
```
Uncaught TypeError: L is not a function
```
To reproduce just load a map and click on COMM maximize button.

Seems to be a name conflict — in minified version of the gen_dashboard_NNNNNNNNN.js global  `L` is bound to some base function, while IITC uses `L` for Leaflet.

All plugins are disabled.
IITC version is 0.25.2

**Comment by jonatkins** [comment] 2015-10-13 02:49
duplicate of #964

**Closed by jonatkins** 2015-10-13 02:49 UTC
